# Generated by Django 4.2.11 on 2024-03-19 14:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('desc', models.TextField()),
                ('ability', models.CharField(max_length=50)),
                ('armor_weapon', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('speed', models.CharField(max_length=50)),
                ('strength', models.CharField(max_length=50)),
                ('wisdom', models.CharField(max_length=50)),
                ('charisma', models.CharField(max_length=50)),
                ('dexterity', models.CharField(max_length=50)),
                ('constitution', models.CharField(max_length=50)),
                ('intelligence', models.CharField(max_length=50)),
                ('danger', models.CharField(max_length=50)),
                ('languages', models.TextField()),
                ('senses', models.TextField()),
                ('armor_class', models.TextField()),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/img/')),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('age', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('speed', models.CharField(max_length=30)),
                ('languages', models.CharField(max_length=30)),
                ('subraces', models.CharField(max_length=30)),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/img/')),
            ],
        ),
        migrations.CreateModel(
            name='User_dialogues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('character_name', models.CharField(max_length=30)),
                ('character_background', models.CharField(blank=True, max_length=500, null=True)),
                ('setting', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='static/img/')),
                ('history', models.TextField(blank=True, null=True)),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='static/img/profile')),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('text', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dialogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_input', models.TextField()),
                ('ai_output', models.TextField()),
                ('ai_img', models.ImageField(blank=True, null=True, upload_to='static/img/')),
                ('ud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dnd.user_dialogues')),
            ],
        ),
    ]
